### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-barbara-chaves#1]
Un trabajo PERFECTO @barbara-chaves  !

Algunas pistas para acabarlo:

## React
- [x] Usa el `id` de cada pokemon para el `key` de react cuando mapeas y creas un listado de componentes
- [x] Mover `li` fuera del componente 'Pokemon', de esta manera es una tarjeta simple que podemos usar en cualquier lugar, no solo dentro de un 'ul` (opcional)
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.

## HTML

- [x] Revise los metadatos en index.html (lang, title ...)

## Otros

- [x] Elimina archivos sin usar y sus referencias: App.css

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by barbara-chaves** [comment]
I think it's all solved. I have made a pull request with the changes. If there is something else to improve, please let me know.

**Comment by migueldelmazo** [comment]
This is amazing. I didn't expect such a good job from any of you. I really like this function !!! 

https://github.com/Adalab/m3-evaluacion-intermedia-barbara-chaves/blob/master/src/components/App.js#L28

**Comment by migueldelmazo** [comment]
You have a very original point of view. It shows that you are able to think in many different ways.
- https://github.com/Adalab/m3-evaluacion-intermedia-barbara-chaves/blob/master/src/components/App.js#L76
- https://github.com/Adalab/m3-evaluacion-intermedia-barbara-chaves/blob/master/src/components/%20PokeList.js#L7

**Comment by migueldelmazo** [comment]
Thank you for making the bonuses!!
